# Generated by Django 3.0.6 on 2020-05-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200525_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'autor', 'verbose_name_plural': 'autorzy'},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='autor recenzji')),
                ('content', models.TextField(verbose_name='treść recenzji')),
                ('is_recommended', models.BooleanField(verbose_name='polecam innym')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='recenzowana książka')),
            ],
            options={
                'verbose_name': 'recenzja',
                'verbose_name_plural': 'recenzje',
            },
        ),
    ]
